 version: '2'
 services:
   dashboard:
     build: .
     ports:
      - "8080:8080"
     depends_on:
      - redis
      - api
      - scaling
   api:
     build:
       context:  ..\elastic-api\
     image: djbnjack/elastic-api:latest
     ports:
      - "3000:3000"
     depends_on:
      - redis
   redis:
     image: redis
   scaling:
     build:
       context:  ..\elastic-scaling\
     image: djbnjack/elastic-scaling:latest
     ports:
      - "8888:8888"