 version: '2'
 services:
   dashboard:
     build: .
     ports:
      - "8080:8080"
     depends_on:
      - redis
      - api
   api:
     image: djbnjack/elastic-api
     ports:
      - "3000:3000"
     depends_on:
      - redis
   redis:
     image: redis
