 version: '2'
 services:
   dashboard:
     build: .
     ports:
      - "8080:8080"
     depends_on:
      - redis
      - api
      - scaling
      - docker
      - scheduler
   api:
     build:
       context:  ..\elastic-api\
     image: djbnjack/elastic-api:latest
     ports:
      - "3000:3000"
     depends_on:
      - redis
   redis:
     image: redis
   scaling:
     build:
       context:  ..\elastic-scaling\
     image: djbnjack/elastic-scaling:latest
     ports:
      - "8888:8888"
     depends_on:
      - docker
      - api
   scheduler:
     build:
       context:  ..\elastic-scheduler\
     image: djbnjack/elastic-scheduler:latest
     depends_on:
      - api
     ports:
      - "3210:3210"
   docker:
     build:
       context: ..\elastic-docker\
     image: djbnjack/elastic-docker:latest
     depends_on:
      - scheduler
     ports:
      - "4444:4444"
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock