 version: '3'
 services:
   dashboard:
     build: .
     ports:
      - "4200:4200"
      - "35729:35729"
     depends_on:
      - dashboardapi
   dashboardapi:
     build:
       context: ..\elastic-dashboard-api\
     image: djbnjack/elastic-dashboard-api:latest
     ports:
      - "8080:8080"
     depends_on:
      - redis
      - api
      - scaling
      - docker
      - scheduler
      - human
   api:
     build:
       context:  ..\elastic-api\
     image: djbnjack/elastic-api:latest
     ports:
      - "3000:3000"
     depends_on:
      - redis
   redis:
     ports:
      - "6379:6379"
     image: redis
   scaling:
     build:
       context:  ..\elastic-scaling\
     image: djbnjack/elastic-scaling:latest
     env_file:
      - ..\scaling-variables.env     
     ports:
      - "8888:8888"
     depends_on:
      - docker
      - api
   scheduler:
     build:
       context:  ..\elastic-scheduler\
     image: djbnjack/elastic-scheduler:latest
     depends_on:
      - api
      - scaling
      - docker
     ports:
      - "3210:3210"
   docker:
     build:
       context: ..\elastic-docker\
     image: djbnjack/elastic-docker:latest
     ports:
      - "4444:4444"
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   human:
     build:
       context: ..\elastic-human\
     image: 'djbnjack/elastic-human:latest'
     depends_on:
      - scheduler
     ports:
      - '5555:5555'