 version: '3'
 services:
   dashboard:
     build: dashboard/
     ports:
      - "4200:4200"
      - "35729:35729"
     depends_on:
      - dashboardapi
   dashboardapi:
     build:
       context: dashboard-api/
     ports:
      - "8080:8080"
     depends_on:
      - redis
      - workflows
      - scaling
      - docker
      - scheduler
      - human
   workflows:
     build:
       context:  workflows/
     ports:
      - "3000:3000"
     depends_on:
      - redis
   redis:
     ports:
      - "6379:6379"
     image: redis
   scaling:
     build:
       context:  scaling/
     env_file:
      - ../scaling-variables.env     
     ports:
      - "8888:8888"
   scheduler:
     build:
       context:  scheduler/
     ports:
      - "3210:3210"
   docker:
     build:
       context: docker/
     env_file:
      - ../docker-variables.env
     ports:
      - "4444:4444"
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   human:
     build:
       context: human/
     ports:
      - '5555:5555'
